Adding systemd service
golemfactory/ya-installer pull request #28
Opened 2022-04-21 07:57 UTC by SGC41

adding golemsp-systemd-updater.sh to install.sh for installation of systemd service with the standard golemsp install script.

hope this isn't totally terrible....

2022-04-22 10:15 UTC, etam commented
I think it would make more sense to run it as a user unit (https://wiki.archlinux.org/title/Systemd/User, also useful: `loginctl enable-linger`)

2022-04-22 10:57 UTC, SGC41 commented
> I think it would make more sense to run it as a user unit (https://wiki.archlinux.org/title/Systemd/User, also useful: `loginctl enable-linger`)

that makes sense.... i bet that is why my systemd service have been behaving so weird when i disable them lol
not really well versed in all this... ill make the necessary changes, should be a pretty simple change.

2022-04-22 11:30 UTC, nieznanysprawiciel commented
I'm adding to core board for review

2022-04-26 11:56 UTC, mfranciszkiewicz requested changes, later dismissed
Please move `ensurepath "$YA_INSTALLER_BIN"` ahead of the optional service installation part. This will prevent potential installation issues _if_ we introduce provider support for macos (the script `exit`s if `systemctl` cannot be found)

2026-03-13 11:29 UTC, closed without merging